name: Sync Card Labeler

description: GitHub actions that automatically labels Issues or PullRequests based on project card moves with bidirectional sync support.

author: Xikaro

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false
  CONFIG_FILENAME:
    description: Config file name.
    default: 'card-labeler.yml'
    required: false
  SEARCH_PROJECT_BY_REGEXP:
    description: Whether to search project name by regular expression.
    default: ''
    required: false
  SEARCH_PROJECT_REGEXP_FLAGS:
    description: RegExp flags for project.
    default: ''
    required: false
  SEARCH_COLUMN_BY_REGEXP:
    description: Whether to search column name by regular expression.
    default: ''
    required: false
  SEARCH_COLUMN_REGEXP_FLAGS:
    description: RegExp flags for project.
    default: ''
    required: false
  PROJECT_CONFIG_IS_REQUIRED:
    description: Whether to throw an error if project's configuration is not found.
    default: 'true'
    required: false
  ENABLE_LABELS_TO_PROJECT:
    description: Enable bidirectional sync from labels to project cards.
    default: 'true'
    required: false

branding:
  icon: 'tag'
  color: 'blue'

runs:
  using: node16
  main: lib/main.js
